---ex01
SELECT NAME FROM CITY
WHERE POPULATION>120000 AND COUNTRYCODE='USA';
---ex02
SELECT * FROM CITY
WHERE COUNTRYCODE='JPN';
---ex03
SELECT CITY, STATE FROM STATION
WHERE LAT_N !=0 AND LONG_W !=0;
---ex04
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%';
---ex05
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u';
---ex06
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'A%'
AND CITY NOT LIKE 'E%'
AND CITY NOT LIKE 'I%'
AND CITY NOT LIKE 'O%'
AND CITY NOT LIKE 'U%';
---ex07
SELECT NAME FROM EMPLOYEE
ORDER BY NAME ASC;
---ex08
SELECT NAME FROM EMPLOYEE
WHERE SALARY > 2000 AND MONTHS < 10
ORDER BY EMPLOYEE_ID ASC
---ex09
SELECT product_id  FROM Products
WHERE low_fats='Y'
AND recyclable='y'
---ex10
SELECT NAME FROM customer
WHERE referee_id IS NULL OR referee_id=1;
---ex11
SELECT NAME, AREA, POPULATION FROM WORLD
WHERE area >3000000 OR population >25000000
---ex12
SELECT DISTINCT author_id AS ID FROM Views
WHERE  author_id=viewer_id
ORDER BY author_id ASC
---ex13

---ex14
SELECT * FROM lyft_drivers
WHERE yearly_salary <=30000 OR yearly_salary >=70000
---ex15

